package engine

import (
	"fmt"
	"regexp"
	"strings"
)

// OutputFormat represents an output format type
type OutputFormat string

const (
	FormatANSI     OutputFormat = "ansi"
	FormatPlain    OutputFormat = "plain"
	FormatMarkdown OutputFormat = "markdown"
	FormatHTML     OutputFormat = "html"
)

// MarkdownRenderer renders markdown to terminal-friendly ANSI output
type MarkdownRenderer struct{}

// RenderToANSI converts markdown text to ANSI-colored terminal output
func (mr *MarkdownRenderer) RenderToANSI(md string) string {
	lines := strings.Split(md, "\n")
	var result []string

	inCodeBlock := false
	codeLang := ""

	for _, line := range lines {
		// Code blocks
		if strings.HasPrefix(line, "```") {
			if inCodeBlock {
				inCodeBlock = false
				result = append(result, "\033[0m") // reset
			} else {
				inCodeBlock = true
				codeLang = strings.TrimPrefix(line, "```")
				if codeLang != "" {
					result = append(result, fmt.Sprintf("\033[90m─── %s ───\033[0m", codeLang))
				}
			}
			continue
		}

		if inCodeBlock {
			result = append(result, "\033[36m"+line+"\033[0m") // cyan for code
			continue
		}

		// Headers
		if strings.HasPrefix(line, "# ") {
			result = append(result, "\033[1;37m"+strings.TrimPrefix(line, "# ")+"\033[0m")
			continue
		}
		if strings.HasPrefix(line, "## ") {
			result = append(result, "\033[1;37m"+strings.TrimPrefix(line, "## ")+"\033[0m")
			continue
		}
		if strings.HasPrefix(line, "### ") {
			result = append(result, "\033[1m"+strings.TrimPrefix(line, "### ")+"\033[0m")
			continue
		}

		// Bullet points
		if strings.HasPrefix(line, "- ") || strings.HasPrefix(line, "* ") {
			result = append(result, "  "+line)
			continue
		}

		// Inline formatting
		line = renderInlineFormatting(line)
		result = append(result, line)
	}

	return strings.Join(result, "\n")
}

// RenderToHTML converts markdown to basic HTML
func (mr *MarkdownRenderer) RenderToHTML(md string) string {
	lines := strings.Split(md, "\n")
	var result []string
	result = append(result, "<html><body>")

	inCodeBlock := false

	for _, line := range lines {
		if strings.HasPrefix(line, "```") {
			if inCodeBlock {
				result = append(result, "</code></pre>")
				inCodeBlock = false
			} else {
				lang := strings.TrimPrefix(line, "```")
				result = append(result, fmt.Sprintf(`<pre><code class="%s">`, lang))
				inCodeBlock = true
			}
			continue
		}

		if inCodeBlock {
			result = append(result, htmlEscape(line))
			continue
		}

		if strings.HasPrefix(line, "# ") {
			result = append(result, "<h1>"+htmlEscape(strings.TrimPrefix(line, "# "))+"</h1>")
		} else if strings.HasPrefix(line, "## ") {
			result = append(result, "<h2>"+htmlEscape(strings.TrimPrefix(line, "## "))+"</h2>")
		} else if strings.HasPrefix(line, "### ") {
			result = append(result, "<h3>"+htmlEscape(strings.TrimPrefix(line, "### "))+"</h3>")
		} else if strings.HasPrefix(line, "- ") {
			result = append(result, "<li>"+htmlEscape(strings.TrimPrefix(line, "- "))+"</li>")
		} else if line == "" {
			result = append(result, "<br/>")
		} else {
			result = append(result, "<p>"+htmlEscape(line)+"</p>")
		}
	}

	result = append(result, "</body></html>")
	return strings.Join(result, "\n")
}

func renderInlineFormatting(line string) string {
	// Bold **text**
	reBold := regexp.MustCompile(`\*\*(.+?)\*\*`)
	line = reBold.ReplaceAllString(line, "\033[1m$1\033[0m")

	// Italic *text*
	reItalic := regexp.MustCompile(`\*(.+?)\*`)
	line = reItalic.ReplaceAllString(line, "\033[3m$1\033[0m")

	// Inline code `text`
	reCode := regexp.MustCompile("`([^`]+)`")
	line = reCode.ReplaceAllString(line, "\033[36m$1\033[0m")

	return line
}

func htmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "\"", "&quot;")
	return r.Replace(s)
}

// ExportToHTML exports conversation messages to an HTML file
func ExportToHTML(messages []Message) string {
	mr := &MarkdownRenderer{}
	_ = mr
	var sb strings.Builder
	sb.WriteString("<html><head><style>body{font-family:monospace;max-width:800px;margin:auto;padding:20px}")
	sb.WriteString(".user{background:#e3f2fd;padding:10px;margin:5px 0;border-radius:5px}")
	sb.WriteString(".assistant{background:#f5f5f5;padding:10px;margin:5px 0;border-radius:5px}")
	sb.WriteString("</style></head><body><h1>BujiCloudCoder Conversation</h1>")

	// Messages would be rendered here based on the types.Message format
	sb.WriteString("<p><em>Export generated by bc2</em></p>")
	sb.WriteString("</body></html>")
	return sb.String()
}

// Message alias for formatting (avoid import cycle)
type Message = struct {
	Role    string
	Content string
}
