package tools

import (
	"github.com/TechnoAllianceAE/buji-cloudcoder/internal/types"
)

// BriefTool generates brief summaries
type BriefTool struct{}

func NewBriefTool() *BriefTool { return &BriefTool{} }
func (t *BriefTool) Name() string { return "Brief" }
func (t *BriefTool) Description() string {
	return `Generates a brief summary or status update. Use this to provide concise overviews of completed work, current state, or session progress.`
}
func (t *BriefTool) InputSchema() map[string]any {
	return map[string]any{
		"type": "object",
		"properties": map[string]any{
			"topic": map[string]any{
				"type":        "string",
				"description": "What to brief about",
			},
			"style": map[string]any{
				"type":        "string",
				"enum":        []string{"bullet", "prose", "oneliner"},
				"description": "Output style (default: bullet)",
			},
		},
		"required": []string{"topic"},
	}
}
func (t *BriefTool) IsReadOnly(_ map[string]any) bool { return true }
func (t *BriefTool) Execute(input map[string]any, ctx *ToolContext) types.ToolResult {
	topic, _ := input["topic"].(string)
	if topic == "" {
		return types.ToolResult{Content: "Error: topic is required", IsError: true}
	}
	// The brief content is generated by the model itself — this tool
	// is a signal that the model should produce a brief output
	return types.ToolResult{Content: "Brief requested for: " + topic}
}
